### PR TITLE
Events search name

### LINKED ISSUE #136: 📖 As Busy Welfare IC, I can search for events by details
...so that I can find similar events to refer to for planning.

________________________________________________________________
### Describe the feature
*Define precisely the desired behavior.*

________________________________________________________________
### Additional context
*What is the current implementation, and the required scope of work?*

### PR DESCRIPTION
**Pull request by Ellevy**
Implemented search for events by name and detail. Includes `--exact` and `--any`. 
Implemented sort for events by `Name` and `EventDate` (look at the note below).

Command to test:
`elist [--exact] [--any] [-n NAME] [-r DETAIL] ... [-s SORT] [-o ORDER]`

Notes: Yet to implement sorting based on upcoming events and searching based on date. Have not added tests yet.

Disclaimer: Removed the unused line for `KEYWORD_MATCHING_MEIER = "Meier"` in files ` TypicalEvents.java` and `TypicalPersons.java`. Not related to the main goal of this PR. Was just lazy to create another PR to remove those 2 lines.

Closes #136 #142

### CODE REVIEW

**Review by garyljj — APPROVED** [review]
Tested, LGTM

**Comment by zhengruoxin** [comment]
When the user input invalid parameters after a flag, the result is the same as `elist` and also displays a "Listed all events" success message. Optional though can consider to display another message to remind them about the missing field (can be error or just a message).
eg. `elist --any sdjsjhf`, or `elist --exact xcvxg`

(Actually this behaviour is also in `list` for persons haha can leave it or do "for fun" next time if want)

**Comment by Ellevy** [comment]
> Currently all successful elist actions display "Listed all events" as the result message. Should we specify them? for eg. "Listed all events in chronological order", or "Listed all events in ascending name order".

For this I believe its the same as `list`. I guess if want can change but must change for both. Maybe I open an issue for changing the output message for both `list` and `elist` to do later on? Then if this one no other issues then can merge first.

**Review by zhengruoxin — APPROVED** [review]
LGTM

**Pull request merged**
