### PR TITLE
Change Phone, Email and Address to Optional Fields

### LINKED ISSUE #72: Change Phone Number, Email, Address, Tags and Birthday to optional fields.
Not compulsory for all contacts to have all these information. Only name is compulsory.

### PR DESCRIPTION
**Pull request by Ellevy**
Allow user to add contact with only name field present.

Fixes #72

### CODE REVIEW

**Comment by pyuxiang** [comment]
According to the UserGuide, we're also removing the need for `-n` to specify the name, i.e. `add John` instead of `add -n John`, but not yet implemented. We can open a separate issue for this.

image

**Review by pyuxiang — APPROVED** [review]
LGTM

**Comment by pyuxiang** [comment]
Issue #81 opened to address the `-n` prefix issue.

**Review by garyljj — APPROVED** [review]
LGTM

**Pull request merged**
