### PR TITLE
Restrict names and tags length

### LINKED ISSUE #223: 🐞 Clipping of details when excessively long tags are supplied
### Describe the issue
*What is expected to happen? How can it be reproduced?*

An artificially long tag will cause the contact list box to expand horizontally beyond the constraints of the contact list. See below for behavior. In particular, there is no option for user to scroll horizontally.

image

________________________________________________________________
### Additional context
*Suggest possible bug sources (or [reference them](https://docs.github.com/en/github/managing-your-work-on-github/opening-an-issue-from-code)). Add screenshots if applicable.*

To fix, perhaps either document this behavior, or we can restrict tags to a reasonable length. For the latter, given the current minimum window width, I'd suggest a length cap of 41, since beyond which the tag itself can start clipping inadvertently, see screenshot below tested using widest alphanumeric `W`:

image

________________________________________________________________
### Environment
 - OS: Windows 10
 - JDK version: 11

### LINKED ISSUE #274: [PE-D] Bug: Done indication does not show up on event with a long name
Done indication does not show up on event with a long name, defeating the purpose of the done functionality in such cases, because users have no way of knowing that the event is done by looking at the gui.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: LimJunxue/ped#8

### PR DESCRIPTION
**Pull request by zhengruoxin**
Fixes #274, fixes #223.

Previously:
Screenshot 2021-04-05 at 09 21 35
Names and tags truncated when length is too long. Done status does not show up beside too long event names.

Now:
Screenshot 2021-04-05 at 09 23 10
Screenshot 2021-04-05 at 09 23 52
Throws error when input names or tags are too long, so they will never be cut off in display.

### CODE REVIEW

**Comment by pyuxiang** [comment]
Should the `isTooLong` method calls be in the constructor instead of the parser? Otherwise direct initialization of names and tags will not trigger the check.

**Comment by pyuxiang** [comment]
Need to truncate further, by taking into account the vertical scrollbar:

image

Optimal length for tags is 41 characters, names is 28 characters.

**Comment by zhengruoxin** [comment]
> Should the `isTooLong` method calls be in the constructor instead of the parser? Otherwise direct initialization of names and tags will not trigger the check.

Oh yes, thanks for pointing it out!

**Comment by Ellevy** [comment]
> Need to truncate further, by taking into account the vertical scrollbar:
> 
> image
> 
> Optimal length for tags is 41 characters, names is 28 characters.
> 
> edit: I'm on Windows 10 with a 1080p screen, is this the same behavior across screen resolutions and platforms?
> Also noticed the font @zhengruoxin is using doesn't seem to be Tisa Sans.


Max name length of 22 and tag length of 35 works well for me!

image

**Review by garyljj — APPROVED** [review]
LGTM

**Comment by pyuxiang** [comment]
Fixes #223

**Review by pyuxiang — APPROVED** [review]
LGTM

**Pull request merged**
