### PR TITLE
Prevent display from returning back to main list after edit

### LINKED ISSUE #251: [PE-D] Automatic return to main view
I ran the following commands after adding "James Hoe" in the previous issue.
`list -n James`

`edit 2 James Lew`

As seen in the pictures, the app automatically returns to the main view(listing every contacts), which may catch the user by surprise.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: linhns/ped#3

### PR DESCRIPTION
**Pull request by zhengruoxin**
Fixes #251.

Previously: every successful edit action displays the full list of contacts back to the user.
Now: displayed contacts list remain as filtered list after successful edit actions done to a filtered list
("edit" applies to both `edit` and `eedit`)

### CODE REVIEW

**Comment by pyuxiang** [comment]
LGTM

**Review by pyuxiang — APPROVED** [review]

**Comment by pyuxiang** [comment]
The same behavior persists for `add` and `eadd` as well, are we fixing those?

**Review by garyljj — APPROVED** [review]
LGTM

**Comment by garyljj** [comment]
> The same behavior persists for `add` and `eadd` as well, are we fixing those?

@pyuxiang Unfortunately for those commands i think is inevitable. Cos wouldnt make sense to not show the contact that u just added.

unless,  one way could be to retrieve the predicate and `.or()` the added user?
Maybe create an issue if we decide that this is a bug

**Pull request merged**
