### PR TITLE
Implement partial and exact list filtering

### LINKED ISSUE #114: 📖 As an experienced user, I can search for contacts by both partial or exact matches
...so that I can have more granularity in filtering.

________________________________________________________________
### Describe the feature
*Define precisely the desired behavior.*

This specific list behavior as part of #102:
`list --partial -n NAME -t TAG (list partial match for all parameters)`

- Collapsing `find` feature and integrate into `list`
- Implement exact matching of names / tags

In particular, typical usage for partial match to filter by tag subcategory, or searching for a specific contact based on vague (name / tag) details. Typical usage for exact match is when filtering a specific subgroup of people (usually by tags).

________________________________________________________________
### Additional context
*What is the current implementation, and the required scope of work?*

Partial matching is implemented, with boolean AND queries across name and specified tags, inside `find`.

### PR DESCRIPTION
**Pull request by pyuxiang**
Adds the specific features specified exactly in the tP document, and documentation updated. Fixes #114.
Detailed description can be found in the user guide.

Syntax to test: `list [--partial] [--any] [-n NAME]... [-t TAG]... [-s SORT_ORDER]`
Features from `find` were partially ported over, including the terminology used for sorting.

### CODE REVIEW

**Comment by garyljj** [comment]
Is partial search not going to be the default?

**Comment by pyuxiang** [comment]
Depends on which we choose to implement. The alternative, with perhaps the flag `--exact`, is also viable.

**Comment by garyljj** [comment]
Yup that might be better. Since we implemented partial in the first place cos it would be more commonly used.
Even if decide to keep it as exact by default, i think would be good to minimally make it non case-sensitive.

**Comment by pyuxiang** [comment]
> Yup that might be better. Since we implemented partial in the first place cos it would be more commonly used.
> Even if decide to keep it as exact by default, i think would be good to minimally make it non case-sensitive.

Yes, exact is already case-insensitive.

**Comment by pyuxiang** [comment]
Changed default behavior to partial matching as requested by @garyljj.

**Review by garyljj — APPROVED** [review]
Just need to update HelpCommand.java
then LGTM

**Comment by Ellevy** [comment]
Are we going to throw error if the user types in wrong specifications? like eg. `list -partial` or 'list partial' or 'list Bernice'

**Comment by pyuxiang** [comment]
> Are we going to throw error if the user types in wrong specifications? like eg. `list -partial` or `list partial` or `list Bernice`. Currently if i'm not wrong it just ignores and lists all people in the addressbook

Thanks for spotting the bugs, you're absolutely right! At first was thinking of making space for the discussed `list 1 3` syntax, but that's not the scope of this PR. Have added changes to check for the required empty preamble.

Some notes:
- `list -partial` and the other variants above are now invalid.
- `list -partial -n john` will not be valid since the preamble `-partial` exists.
- `list -n john -partial` will be valid since the search term for name is now `john -partial`.
  - This issue cannot be avoided since this is fundamentally how the parser is designed, to only parse specified prefixes.
  - One way is to enforce regex validation, but we probably can't predict how [people name themselves / their kids](https://www.washingtonpost.com/technology/2020/05/08/musk-grimes-baby-name/) :')

**Comment by Ellevy** [comment]
LGTM

**Review by Ellevy — APPROVED** [review]
LGTM

**Comment by pyuxiang** [comment]
> Just need to update HelpCommand.java
> then LGTM

Great catch, thanks! Let's defer this till once the `list` functionality is complete, since there are more pending changes to the command.

**Pull request merged**
