### PR TITLE
Personalise ab3 to HippoCampus

### LINKED ISSUE #83: 💡  Personalise address book to HippoCampus
### Describe the issue
*What is the problem, if any? What is the desired behavior?*
Replace all instances of address book to HippoCampus

________________________________________________________________
### Additional context
*Describe possible and/or alternative solutions, to highlight required scope of work.*

### PR DESCRIPTION
**Pull request by garyljj**
Replace package from seedu.addresss -> seedu.hippocampus
Replace most instances of address book in the app to HippoCampus

I didnt replace EVERY SINGLE instance of address book with HippoCampus
cos many are referring to address book as a THING rather than the NAME of the app.

I also didnt touch many of the md such as tutorial md and setting up md

Closes #83

### CODE REVIEW

**Review by pyuxiang — DISMISSED** [review]
Did a cursory startup test + running `find`, `delete`, `add`, `edit`. Looks okay.

**Comment by pyuxiang** [comment]
Note that merging this is a big priority - will introduce a lot of merge conflicts with subsequent PRs.

**Review by Ellevy — APPROVED** [review]
LGTM

**Review by pyuxiang — APPROVED** [review]
LGTM

**Pull request merged**
