### PR TITLE
Fix unclear error msg for already done events

### LINKED ISSUE #242: [PE-D] edone command throwing invalid index warning when used on events that are already done
The `edone 1` comment threw an invalid index warning when I used it on an event that was already done. However, the index provided was valid.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: danielonges/ped#4

### PR DESCRIPTION
**Pull request by garyljj**
Fixes #242 

1. `Invalid event index(es): %s` -> `Invalid/Already completed event index(es): %s`
2. `None of the indexes provided are valid` -> `All index(es) provided are invalid/already completed`

1
image

2
image

### CODE REVIEW

**Comment by pyuxiang** [comment]
Indexes are not exactly completed for 2. Perhaps can change wording to:
`Indexes provided are either invalid, or reference events that are already completed.`

**Comment by pyuxiang** [comment]
Other than the above, LGTM.

**Review by pyuxiang — APPROVED** [review]

**Comment by garyljj** [comment]
Rephrased error message as suggested by @pyuxiang 

image

**Review by zhengruoxin — APPROVED** [review]
LGTM

**Pull request merged**
