### PR TITLE
Add UndoCommand Feature

### LINKED ISSUE #101: 📖 As a clumsy user, I can undo commands
...so that I can rectify mistakes when calling the wrong commands in the app.

________________________________________________________________
### Additional context
*Describe possible implementations, to highlight required scope of work.*

@garyljj has an idea.

### PR DESCRIPTION
**Pull request by nickyfoo**
Add a StateHistory class to keep track of the states of the address book as it changes, and an UndoCommand to make use of this.

Fixes #101.

### CODE REVIEW

**Comment by pyuxiang** [comment]
What's the syntax to test this?

**Comment by pyuxiang** [comment]
`INFO: Added state to stateHistory. Current number of states is: 2. Currently on state: 1` is the logged message. Seems like we can have a feature to easily `redo` as well.

**Review by pyuxiang — APPROVED** [review]
LGTM

**Comment by nickyfoo** [comment]
> `INFO: Added state to stateHistory. Current number of states is: 2. Currently on state: 1` is the logged message. Seems like we can have a feature to easily `redo` as well.

Yup, definitely planning to in a future iteration. I mentioned it in a currently unimplemented nextState method in StateHistory

**Review by garyljj — APPROVED** [review]
LGTM

**Pull request merged**
