### PR TITLE
Update Error Message when index specified as 0

### LINKED ISSUE #263: [PE-D] Error message regarding TAB
for `eedit` : when `TAB` is pressed after an incorrect event index is provided: 

when `TAB` is pressed after typing `eedit 0 -n`

Perhaps the first error message can be used in the case of the second error message.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: khiaxeng/ped#10

### PR DESCRIPTION
**Pull request by glennljs**
When command `eedit 0 TAB` is run, change return error message from "Index not specified!" to "Index not specified or Invalid!".

Closes #263

### CODE REVIEW

**Review by garyljj — APPROVED** [review]
LGTM

**Review by zhengruoxin — APPROVED** [review]
The new message is clearer, though do we want to standardise with the other invalid index message? eg. 0 and 20 are both "invalid indexes" but show different error messages. But both works lah
Screenshot 2021-04-05 at 16 12 36
Screenshot 2021-04-05 at 16 12 46

**Comment by Ellevy** [comment]
I would prefer it if both of these give the same error message.

image

image

Perhaps can change line 49  in `EEditAutocompleteUtil.java` to 
`throw new ParseException(INDEX_NOT_SPECIFIED_OR_INVALID_MESSAGE);`.

Also agree with @zhengruoxin's comment. Maybe we standardize for both `eedit` and `edit` to `Index not specified or invalid!`

**Comment by garyljj** [comment]
> The new message is clearer, though do we want to standardise with the other invalid index message? eg. 0 and 20 are both "invalid indexes" but show different error messages. But both works lah

Technically not same case leh, cos 0 is not valid index (same case with `-1`, `abc` etc) but 20 is a valid index that is not in the addressbook.
Thats why 0 causes "index invalid" but 20 causes "person index provided is invalid"

But idk maybe can somehow make clearer haha

**Comment by Ellevy** [comment]
> > The new message is clearer, though do we want to standardise with the other invalid index message? eg. 0 and 20 are both "invalid indexes" but show different error messages. But both works lah
> 
> Technically not same case leh, cos 0 is not valid index (same case with `-1`, `abc` etc) but 20 is a valid index that is not in the addressbook.
> Thats why 0 causes "index invalid" but 20 causes "person index provided is invalid"
> 
> But idk maybe can somehow make clearer haha

TBH 'index invalid" and "person index provided is invalid" sounds the same to me. What about

-ve indexes/0: "Index is not specified or invalid: Please enter an index value larger than 0"
too big index: "Index provided is too large: Please enter a valid index from the list"

**Comment by glennljs** [comment]
Invalid Index:
Screenshot 2021-04-07 at 4 56 09 PM

Out of Bounds Index:
Screenshot 2021-04-07 at 4 56 32 PM

**Review by Ellevy — APPROVED** [review]
LGTM

**Pull request merged**
