### PR TITLE
Add functionality to sort by birthday

### LINKED ISSUE #125: 📖 As a welfare IC, I can sort contacts based on their birthday
...so that I can know the order in which birthdays should be celebrated.

________________________________________________________________
### Describe the feature
*Define precisely the desired behavior.*

Overload `list` to include sorting by birthday, either ascending or descending order.

________________________________________________________________
### Additional context
*What is the current implementation, and the required scope of work?*

### PR DESCRIPTION
**Pull request by pyuxiang**
### Important note

~~**Should not be merged immediately: contingent on pull requests #116 and #119 being merged**, due to feature dependencies. Otherwise the changes to be reviewed will be too numerous to process.~~ Relevant PRs have been merged.

### Description

Closes #125.
* Adds comparator to sort by birthday as well, which sorts by month and day (ignores year).
* Ordering of sorting (i.e. ascending, descending) is decoupled from the sort parameter (i.e. name, birthday), to allow easy extensibility, e.g. sorting by other parameters.
* Refactoring of predicate merging method (shifted into parser instead).

### Test syntax

`list [...] --sort name --order descending`
* `-s` is an alias for `--sort`, `-o` is an alias for `--order`
* Sort fields include `name` (`n`) and `birthday` (`b`)
* Sort orders include `ascending` (`a`, `asc`) and `descending` (`d`, `des`, `desc`)

### Notable behavior: Birthday sorting for people with no birthdays

Since birthday sort may be specified even when all filtered people do not contain birthdays, empty birthdays are sorted at the very top of an ascending birthday sorted list.

image

An alternative includes excluding such people in the first place, but leaving such people in has its benefits from the perspective of a welfare IC:

1. People who should have birthdays populated, but do not, are immediately surfaced.
2. When contact list is tagged properly, `list` can filter people associated with a certain tag, that already have birthdays specified.

### Notable behavior: Case-sensitive name sorting

Since comparison is performed without conversion to lowercase, the order of list sorted by name will be in ASCII order, e.g. "A" < "J" < "a". If sorting by lowercase is desired, this can be implemented as a subsequent feature enhancement.

image

### Required follow-up:

* Update documentation for birthday sorting feature, and sort/order syntax.
* Update help command for `list`.

### CODE REVIEW

**Comment by Ellevy** [comment]
Do we want to allow sorting based on multiple conditions? eg. I have 2 people of the same birthday and I want to sort based on ascending name then descending birthday. If we do not want to allow it then should we throw an error when a person inputs more than 1 `-s`?

**Comment by pyuxiang** [comment]
> Do we want to allow sorting based on multiple conditions? eg. I have 2 people of the same birthday and I want to sort based on ascending name then descending birthday. If we do not want to allow it then should we throw an error when a person inputs more than 1 `-s`?

Probably not, since it increases the complexity of the command + the parser doesn't distinguish the absolute positions of the prefixes, so matching two prefixes will be a pain.

Throwing error is one way, and the ~~easy way out~~ other way would be to simply document this ~~behavior~~ feature (i.e. only the last sort prefix given is used), just like for the `add` command. Which do you prefer?

**Comment by Ellevy** [comment]
> > Do we want to allow sorting based on multiple conditions? eg. I have 2 people of the same birthday and I want to sort based on ascending name then descending birthday. If we do not want to allow it then should we throw an error when a person inputs more than 1 `-s`?
> 
> Probably not, since it increases the complexity of the command + the parser doesn't distinguish the absolute positions of the prefixes, so matching two prefixes will be a pain.
> 
> Throwing error is one way, and the ~easy way out~ other way would be to simply document this ~behavior~ feature (i.e. only the last sort prefix given is used), just like for the `add` command. Which do you prefer?

I think documenting is good! Which do you prefer

**Review by Ellevy — APPROVED** [review]
LGTM

**Comment by garyljj** [comment]
> Throwing error is one way, and the ~easy way out~ other way would be to simply document this ~behavior~ feature (i.e. only the last sort prefix given is used), just like for the `add` command. Which do you prefer?

"If a parameter is expected only once in the command, but you specified it multiple times, only the last occurrence of the parameter will be taken.
e.g. if you specify -p 12341234 -p 56785678, only -p 56785678 will be taken"

Yup our UG already states this case. So alls good!

**Comment by pyuxiang** [comment]
> Do we want to allow sorting based on multiple conditions? eg. I have 2 people of the same birthday and I want to sort based on ascending name then descending birthday. If we do not want to allow it then should we throw an error when a person inputs more than 1 `-s`?

On that note, forgot to mention that if this is desired, there is a workaround for it, e.g. to sort by ascending birthday, and descending name if same birthday, can call these two commands in succession:
1. `list [...] [-s name] -o descending`
2. `list [...] -s birthday [-o ascending]`

**Pull request merged**
